// Generated by https://quicktype.io
class Categorias{
  List<Categoria> items= new List();
  Categorias();
  Categorias.fromJsonList(List<dynamic> jsonList){
    if(jsonList == null){
      return;
    }
    for(var item in jsonList){
      final categoria = new Categoria.fromJsonMap(item);
      //La lista items va a contener toda la lista de categorias mapeadas.
      items.add(categoria);
    }
  }
}

class Categoria {
  String title;
  String data;
  String nameCategory;
  dynamic icon;
  String ctidss;
  int cant;

  Categoria({
    this.title,
    this.data,
    this.nameCategory,
    this.icon,
    this.ctidss
  });

  //Genera una instancia que viene en formato json
  Categoria.fromJsonMap(Map<String,dynamic> json){
    title         = json['title'];
    data          = json['data'];
    nameCategory  =json['name_category'];
    icon          =json['icon'];
    ctidss        = json['_idct'];
    cant          = json['cant'];
  }

  //Método para obtener las imágenes de las categorias
  getImageCategorias(){
    //print(icon);
    if(icon == null){
      return 'https://cdn.samsung.com/etc/designs/smg/global/imgs/support/cont/NO_IMG_600x600.png';
    }else{
      return '${icon.toString()}';
    }
  }
}
