// Generated by https://quicktype.io

/*class DetalleTours {
  String title;
  bool success;
  List<DetalleTour> details=new List();

  DetalleTours();

  //Este constructor recibe todas las respuestas del mapa
  //Se espera recibir la lista de tours
  DetalleTours.fromJsonList(List<dynamic> jsonList){
    if(jsonList == null){
      return;
    }
    for(var item in jsonList){
      final tour = new DetalleTour.fromJsonMap(item);
      //La lista items va a contener la lista de tours recorridos
      details.add(tour);
    }
  }
}*/


// Generated by https://quicktype.io

class DetalleTours {
  String title;
  bool success;
  List<DetalleTour> details = List();

  DetalleTours({
    this.title,
    this.success,
    this.details,
  });

//Este constructor recibe todas las respuestas del mapa
  //Se espera recibir la lista de tours
  DetalleTours.fromJsonList(List<dynamic> jsonList){
    if(jsonList == null){
      return;
    }
    for(var item in jsonList){
      final tour = new DetalleTour.fromJsonMap(item);
      //La lista items va a contener la lista de tours recorridos
      details.add(tour);
    }
  }

}

class DetalleTour {
  String user;
  String name;
  String title;
  String description;
  String recommendations;
  int score;
  String cover;
  int duration;
  String budget;
  int purchases;
  String category;
  String city;
  String state;
  String country;
  List route;

  DetalleTour({
    this.user,
    this.name,
    this.title,
    this.description,
    this.recommendations,
    this.score,
    this.cover,
    this.duration,
    this.budget,
    this.purchases,
    this.category,
    this.city,
    this.state,
    this.country,
    this.route,
  });

  //Voy a llamar cuando quiero generar una instancia que viene en un mapa
  // en formato json
  DetalleTour.fromJsonMap(Map<String,dynamic> json){
    user            = json['user'];
    name            = json['name'];
    title           = json['title'];
    //idtour          = json['idtour'];
    description     = json['description'];
    recommendations = json['recommendations'];
    score           = json['score'];
    cover           = json['cover'];
    duration        = json['duration'];
    budget          = json['budget'];
    purchases       = json['purchases'];
    category        = json['category'];
    country         = json['country'];
    state           = json['state'];
    city            = json['city'];
   // gallery         = json['gallery'];
    route          = json['route'];
  }
}

class Route {
  String idsite;
  String site;
  String lat;
  String lng;
  String description;
  List<Gallery> gallery;

  Route({
    this.idsite,
    this.site,
    this.lat,
    this.lng,
    this.description,
    this.gallery,
  });
}

class Gallery {
  String url;

  Gallery({
    this.url,
  });
}


/*class DetalleTour {
  String user;
  String name;
 // int idtour;
  String title;
  String description;
  String recommendations;
  int score;
  String cover;
  String duration;
  String budget;
  int purchases;
  String category;
  int country;
  int state;
  String city;
  List gallery;
  List route;

  DetalleTour({
    this.user,
    this.name,
    this.title,
    //this.idtour,
    this.description,
    this.recommendations,
    this.score,
    this.cover,
    this.duration,
    this.budget,
    this.purchases,
    this.category,
    this.country,
    this.state,
    this.city,
    this.gallery,
    this.route
  });

  //Voy a llamar cuando quiero generar una instancia que viene en un mapa
  // en formato json
  DetalleTour.fromJsonMap(Map<String,dynamic> json){
    user            = json['user'];
    name            = json['name'];
    title           = json['title'];
    //idtour          = json['idtour'];
    description     = json['description'];
    recommendations = json['recommendations'];
    score           = json['score'];
    cover           = json['cover'];
    duration        = json['duration'];
    budget          = json['budget'];
    purchases       = json['purchases'];
    category        = json['category'];
    country         = json['country'];
    state           = json['state'];
    city            = json['city'];
    gallery         = json['gallery'];
    route          = json['route'];
  }
}*/
