// Generated by https://quicktype.io
class ListAddressComponent{
  List<AddressComponentes> componentes = List();

  ListAddressComponent();

  //Este constructor recibe todas las respuestas del mapa
  //Se espera recibir la lista de tours
  ListAddressComponent.fromJsonList(List<dynamic> jsonList){
    if(jsonList == null){
      return;
    }
    for(var item in jsonList){
      final componente = new AddressComponentes.fromJsonMap(item);
      //La lista items va a contener la lista de tours recorridos
      componentes.add(componente);
    }
  }
}
class AddressComponentes {
  List<dynamic> addressComponents;
  String formattedAddress;
  Map geometry;
  String placeId;
  List<dynamic> types;

  AddressComponentes({
    this.addressComponents,
    this.formattedAddress,
    this.geometry,
    this.placeId,
    this.types,
  });

  //Voy a llamar cuando quiero generar una instancia que viene en un mapa
  // en formato json
  AddressComponentes.fromJsonMap(Map<String,dynamic> json){
    addressComponents   = json['address_components'];
    formattedAddress    = json['formatted_address'];
    geometry            = json['geometry'];
    placeId             = json['place_id'];
    types               = json['types'];
  }

}

class Geometry {
  Bounds bounds;
  Location location;
  String locationType;
  Bounds viewport;

  Geometry({
    this.bounds,
    this.location,
    this.locationType,
    this.viewport,
  });
}

class Bounds {
  Location northeast;
  Location southwest;

  Bounds({
    this.northeast,
    this.southwest,
  });
}

class Location {
  double lat;
  double lng;

  Location({
    this.lat,
    this.lng,
  });
}
