// Generated by https://quicktype.io

/*class TourData {
  bool success;
  String title;
  List<Tour> data;

  TourData({
    this.success,
    this.title,
    this.data,
  });
}*/

class Tours{
  bool success;
  String title;
  List<Tour> items = new List();
  Tours();
  Tours.fromJsonList(List<dynamic> jsonList){
    if(jsonList == null){
      return;
    }
    jsonList.forEach((item){
      final tour = new Tour.fromJsonMap(item);
      //La lista va a contener toda la lista de tours mapeados
      items.add(tour);
    });
  }
}

class Tour {
  String title;
  String description;
  int score;
  String cover;
  String nameCategory;

  String idCity;
  String city;
  String country;

  String gallery;

  Tour({
    this.title,
    this.description,
    this.score,
    this.cover,
    this.nameCategory,

    this.idCity,
    this.city,
    this.country,

    this.gallery
  });

  Tour.fromJsonMap(Map<String,dynamic> json){
    title       = json['title'];
    description = json['description'];
    score       = json['score'];
    cover       = json['cover'];
    nameCategory= json['name_category'];

    idCity      = json['idcity'];
    city        = json['city'];
    country     = json['country'];

    gallery     = json['gallery'];
  }

  //Método para obtener las imagenes de los tours
  getImageTours(){
    if(cover==null){
      return 'https://cdn.samsung.com/etc/designs/smg/global/imgs/support/cont/NO_IMG_600x600.png';
    }else{
      return '$cover';
    }
  }
}


// Generated by https://quicktype.io

/*class Tours {
  
  List<Tour> items = new List();

  Tours();

  Tours.fromJsonList(List<dynamic> jsonList){
    if(jsonList == null){
      return;
    }
    jsonList.forEach((item){
      final tour = new Tour.fromJsonMap(item);
      //La lista va a contener toda la lista de tours mapeados
      items.add(tour);
    });
  }
}*/

/*class Tour {
  String title;
  String description;
  int score;
  String cover;
  String nameCategory;
  List<String> gallery;

  Tour({
    this.title,
    this.description,
    this.score,
    this.cover,
    this.nameCategory,
    this.gallery,
  });

  Tour.fromJsonMap(Map<String,dynamic> json){
    title       = json['title'];
    description = json['description'];
    score       = json['score'];
    cover       = json['cover'];
    nameCategory= json['name_category'];
    gallery     = json['gallery'];
  }
}*/
